apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    role: myrole
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "9999"
